### ISSUE TITLE
Next Milestone for NNVM-Fusion

### ISSUE THREAD

**Issue by ZihengJiang** [dmlc/nnvm-fusion#2]
# Next Milestone for NNVM-Fusion

- Apply NNVM-Fusion on MXNet

## How

- add a set of primitive operations in nnvm, like ewise-op, conv… as tianqi metioned
- refactor fusion based on these primitive operations
- replace corresponding operators in mxnet, apply fusion

**Comment by ZihengJiang** [comment]
@tqchen @jermainewang @mli any suggestion or idea?

**Comment by pineking** [comment]
@ZihengJiang Does this implement on MXNet?

**Comment by ZihengJiang** [comment]
Not yet, but I plan to complete this in the next week considering the situation mentioned in your issue https://github.com/dmlc/mxnet/issues/4878 . Thanks @pineking

**Comment by pineking** [comment]
@ZihengJiang Great job，waiting for this can be merged soon.
